### ISSUE TITLE
Foundation issue tracker doesn't allow new issues

### ISSUE THREAD

**Issue by ryantheleach** [FoundationDriven/Foundation#40]
I signed up for your redmine but still wasn't able to make an issue.

It's probably just a permissions issue for new users.

**Comment by exstar** [comment]
Thanks, for reporting, i'll see if i can fix the issue.
Moreover, the Economy API is by far not finished, development on it will continue. Thanks for your suggestions!

**Comment by OscarOrSomething** [comment]
Could you please put the Economy API improvements in another issue (just here on github). 

I will make a new draft of the Economy API soon, Thank you.

Regarding the issue tracker, We are thinking of switching to another one, our current one isn't very good.


Thanks.

**Comment by OscarOrSomething** [comment]
@exstar Would you be able to apply for JIRA? I think we are viable now.

**Comment by OscarOrSomething** [comment]
We have a JIRA installation but we are having some problems with the public sign up.

**Comment by sam4215** [comment]
@OscarOrSomething we have a JIRA? How long has that existed?

**Comment by exstar** [comment]
@sam4215 since yesterday

**Comment by OscarOrSomething** [comment]
I'm trying to get it fully sorted out but it is up over [here](http://foundationdriven.atlassian.net)
