### ISSUE TITLE
Unimplemented module API / module loading

### ISSUE THREAD

**Issue by exstar** [FoundationDriven/Foundation#47]
The most essential part of the Foundation plugin: module loading/management and its API. Work must be done on this before further development on Foundation. Documentation muse be provided after the design and implementation are finished.

**Comment by sam4215** [comment]
@FoundationDriven/developers I will provide documentation upon completion of these features.

**Comment by exstar** [comment]
@sam4215 Thanks

**Comment by exstar** [comment]
Module loading is finished; a basic, small documentation is needed.

**Comment by sam4215** [comment]
It'll have to wait till Friday im afraid... Sorry

**Comment by exstar** [comment]
No problem
